/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  userSidebar: [{ type: 'autogenerated', dirName: 'user' }],
  devSidebar: [{ type: 'autogenerated', dirName: 'developer' }],
};

module.exports = sidebars;
